"""empty message

Revision ID: 476733d0189
Revises: 4a334605646
Create Date: 2016-01-16 01:07:13.721808

"""

# revision identifiers, used by Alembic.
revision = '476733d0189'
down_revision = '4a334605646'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('location', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'location')
    ### end Alembic commands ###
