"""empty message

Revision ID: 4a334605646
Revises: 4195393723a
Create Date: 2016-01-15 23:09:49.294865

"""

# revision identifiers, used by Alembic.
revision = '4a334605646'
down_revision = '4195393723a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=250), nullable=True))
    op.add_column('item', sa.Column('serial_number', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'serial_number')
    op.drop_column('item', 'name')
    ### end Alembic commands ###
